apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cratos

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - redis.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - pdb.yaml
  - ingress.yaml

commonLabels:
  app.kubernetes.io/part-of: cratos
  app.kubernetes.io/managed-by: kustomize

images:
  - name: cratos
    newName: ghcr.io/cratos/cratos
    newTag: latest
