apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: cratos-pdb
  namespace: cratos
  labels:
    app.kubernetes.io/name: cratos
    app.kubernetes.io/component: availability
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cratos
      app.kubernetes.io/component: server
